// @flow
export const REQUEST_BOOKSHELF: string = 'REQUEST_BOOKSHELF'
export const RECEIVE_BOOKSHELF: string = 'RECEIVE_BOOKSHELF'
export const REQUEST_BOOK: string = 'REQUEST_BOOK'
export const RECEIVE_BOOK: string = 'RECEIVE_BOOK'
export const REQUEST_ADD_BOOK: string = 'REQUEST_ADD_BOOK'
export const RECEIVE_ADD_BOOK: string = 'RECEIVE_ADD_BOOK'
export const REQUEST_LOGIN: string = 'REQUEST_LOGIN'
export const RECEIVE_LOGIN: string = 'RECEIVE_LOGIN'
export const REQUEST_REGISTER: string = 'REQUEST_REGISTER'
export const RECEIVE_REGISTER: string = 'RECEIVE_REGISTER'
export const SET_USER: string = 'SET_USER'
export const DELETE_USER: string = 'DELETE_USER'
export const CHANGE_DRAWER: string = 'CHANGE_DRAWER'
export const SET_DESCRIPTION: string = 'SET_DESCRIPTION'
